# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './clientGui.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(471, 363)
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setGeometry(QtCore.QRect(10, 10, 422, 334))
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.inputTextArea = QtWidgets.QTextEdit(self.widget)
        self.inputTextArea.setObjectName("inputTextArea")
        self.horizontalLayout.addWidget(self.inputTextArea)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.portSpinBox = QtWidgets.QSpinBox(self.widget)
        self.portSpinBox.setMinimum(1024)
        self.portSpinBox.setMaximum(65536)
        self.portSpinBox.setObjectName("portSpinBox")
        self.verticalLayout.addWidget(self.portSpinBox)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.socketPortLabel = QtWidgets.QLabel(self.widget)
        self.socketPortLabel.setObjectName("socketPortLabel")
        self.verticalLayout.addWidget(self.socketPortLabel)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.connectButton = QtWidgets.QPushButton(self.widget)
        self.connectButton.setObjectName("connectButton")
        self.verticalLayout.addWidget(self.connectButton)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem3)
        self.sendButton = QtWidgets.QPushButton(self.widget)
        self.sendButton.setObjectName("sendButton")
        self.verticalLayout.addWidget(self.sendButton)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.uploadFileLabel = QtWidgets.QLabel(self.widget)
        self.uploadFileLabel.setObjectName("uploadFileLabel")
        self.horizontalLayout_2.addWidget(self.uploadFileLabel)
        self.uploadFileLineEdit = QtWidgets.QLineEdit(self.widget)
        self.uploadFileLineEdit.setObjectName("uploadFileLineEdit")
        self.horizontalLayout_2.addWidget(self.uploadFileLineEdit)
        self.uploadToolButton = QtWidgets.QToolButton(self.widget)
        self.uploadToolButton.setObjectName("uploadToolButton")
        self.horizontalLayout_2.addWidget(self.uploadToolButton)
        self.uploadButton = QtWidgets.QPushButton(self.widget)
        self.uploadButton.setObjectName("uploadButton")
        self.horizontalLayout_2.addWidget(self.uploadButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.downloadFileLabel = QtWidgets.QLabel(self.widget)
        self.downloadFileLabel.setObjectName("downloadFileLabel")
        self.horizontalLayout_3.addWidget(self.downloadFileLabel)
        self.downloadFileLineEdit = QtWidgets.QLineEdit(self.widget)
        self.downloadFileLineEdit.setObjectName("downloadFileLineEdit")
        self.horizontalLayout_3.addWidget(self.downloadFileLineEdit)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem4)
        self.downloadButton = QtWidgets.QPushButton(self.widget)
        self.downloadButton.setObjectName("downloadButton")
        self.horizontalLayout_3.addWidget(self.downloadButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.infoLabel = QtWidgets.QLabel(self.widget)
        self.infoLabel.setObjectName("infoLabel")
        self.horizontalLayout_4.addWidget(self.infoLabel)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem5)
        self.disconnectButton = QtWidgets.QPushButton(self.widget)
        self.disconnectButton.setObjectName("disconnectButton")
        self.horizontalLayout_4.addWidget(self.disconnectButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.socketPortLabel.setText(_translate("Dialog", "Socket port"))
        self.connectButton.setText(_translate("Dialog", "Connect"))
        self.sendButton.setText(_translate("Dialog", "Send"))
        self.uploadFileLabel.setText(_translate("Dialog", "Upload"))
        self.uploadToolButton.setText(_translate("Dialog", "..."))
        self.uploadButton.setText(_translate("Dialog", "Upload"))
        self.downloadFileLabel.setText(_translate("Dialog", "Download"))
        self.downloadButton.setText(_translate("Dialog", "Download"))
        self.infoLabel.setText(_translate("Dialog", "info:"))
        self.disconnectButton.setText(_translate("Dialog", "Disconnect"))

